<br>

<form method="POST">
  <div class="input-group rounded">
    <input type="search" class="form-control rounded" placeholder="Search" name="q" />
    <span class="input-group-text border-0" id="search-addon">
      <input type="submit" />
    </span>
  </div>
</form>



<!-- Data -->
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">id</th>
      <th scope="col">Name </th>
      <th scope="col">categoryName</th>
      <th scope="col">price</th>
      <th scope="col">Stock</th>
      <th scope="col">QuickView</th>
      <th scope="col">DelButton </th>
      <th scope="col">EditButton </th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($data as $key => $value) { ?>

      <!-- The Modal -->
      <div class="modal" id="myModal<?php echo $value->_id ?>">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Quick View </h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
              <?php if ($value->labelValue) { ?>

                <?php foreach ($value->labelValue as $k => $v) {
                  echo $k . ':' . $v . '<br>';
                } ?>
              <?php } ?>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

          </div>
        </div>
      </div>
      <!-- End Of Model -->
      <tr>
        <td><?php echo $value->_id; ?></td>
        <td><?php echo $value->name; ?></td>
        <td><?php echo $value->categoryName; ?></td>
        <td><?php echo $value->price; ?></td>
        <td><?php echo $value->stock; ?></td>
        <td>
          <!-- Button to Open the Modal -->
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal<?php echo $value->_id ?>">
            QuickView
          </button>
        </td>
        <td><a href=<?php echo "/products/del/" . $value->_id; ?>>X</a></td>
        <td><a href=<?php echo "/products/edit/" . $value->_id; ?>>Edit</a></td>
      </tr>
    <?php } ?>
  </tbody>
</table>

<?php
$sum = 0;
for ($var = 1; $var < 15; $var++) {
  $sum = $sum + (7 * ($var + 1));
  echo $var . '->' . ($var + 1) . '->' . (7 * ($var + 1)) . '<br>';
}
echo $sum;
?>