<br>

<h1>Order details</h1>


<!-- Data -->
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">id</th>
      <th scope="col">Customer Name </th>
      <th scope="col">QTY</th>
      <th scope="col">Address</th>
      <th scope="col">PROD</th>
      <th scope="col">status</th>
 
    </tr>
  </thead>
  <tbody>
    <?php foreach ($data as $key => $value) { ?>
      <tr>
      <th scope="row"><?php echo $value->_id;?> </th>
      <td><?php echo $value->customer_name;?></td>
      <td><?php echo $value->qty;?></td>
      <td><?php echo $value->address;?></td>
      <td><?php echo $value->prod;?></td>
      <td><?php echo $value->status;?></td>
    </tr>
    <?php } ?>            
  </tbody>
</table>

