<h1>HEY</h1>

<form method="POST">
    <label>Name</label>
    <input type="text" name='name' /> <br>

    <label>Category name</label>
    <input type="text" name='categoryName' /><br>
    <label>Price</label>
    <input type="text" name='price' /><br>
    <label>Stock</label>
    <input type="text" name='stock' /><br>
    <label>Additional fields <span class="buttons" id="addFields"><b> + </b></span></label><br>
    <!-- Dynaicall add this Section -->
    <div id="additionalFields">
    </div>
    
    <br><input type="submit" value="submit">
</form>