<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>mongo Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="<?php echo APP_PATH.'/views/mystyle.css'?>" >
  
    <link rel="stylesheet" href="assets/mystyle.css" >
  
   
</head>

<body>
<div class="container">
    
    <?php echo $this->getContent(); ?>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="assets/mywork.js"></script>
</body>
</html>